### PR TITLE
Allow to configure client_max_body_size to avoid HTTP 413

### PR DESCRIPTION
**Pull request by mazoo**
I am super happy with your work. Ran into some trouble today and thought, my pull request might be helpful for others as well.

### CODE REVIEW

**Comment by ysoldak** [comment]
Thanks! Looks legit and I'll merge it now.
After that I will add a link to the docs and set value to default "1m".

**Comment by mazoo** [comment]
> Thanks! Looks legit and I'll merge it now.
> After that I will add a link to the docs and set value to default "1m".

Hi Yurii

Thanks for accepting my pull request. You missed one detail when you changed the default to 1M though. The 1m should be changed as well in [main.sh](/fareoffice/modsecurity-docker/blob/master/main.sh#L34), otherwise, it will never be detected and therefore has no effect at the moment :(

Could you change that or do you want me to add a new pull request?

Cheers,
Marcel

**Comment by ysoldak** [comment]
You are right, sorry, do not understand how I've missed that. Will fix shortly.

**Comment by ysoldak** [comment]
Shall be good now https://github.com/fareoffice/modsecurity-docker/compare/9fa6ad28616a22f92bd1d8864db9b2f67867a5f8...bfefbfaf94214fb0242d0b5e7b99f60d2020f673

**Pull request merged**
